### ISSUE TITLE
Unexpcted config result while apply multiple 'when'

### ISSUE THREAD

**Issue by tutufool** [lukas-krecan/JsonUnit#234] opened 2020-06-18 09:45 UTC
code like:

```
    	Configuration config = Configuration.empty().when(path("aaa"), thenIgnore()).when(path("bbb"), thenIgnore());
    	
    	System.out.println(config.getPathsToBeIgnored());
```

output is:

`[bbb]`

while I expect it to be:

`[aaa, bbb]`

Is it a bug? looks like the latter one override the previous one?

**Comment by lukas-krecan** [comment] 2020-06-19 05:04
It's a bug caused by unexpected usage pattern. There is `paths()` method for specifying multiple paths.

**Comment by lukas-krecan** [comment] 2020-06-19 05:39
Released as 2.18.1

**Closed by lukas-krecan** 2020-06-19 05:39 UTC
